name: GitHub Actions Demo
on: [push]
env:
  KUBECONFIG_BAS64: ${{ secrets.KUBECONFIG }}
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: xom4ek/actions-test
          # tags: |
          #   type=ref,event=branch
          #   type=ref,event=pr
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - run: |
          mkdir -p ~/.kube/
          export TAG=${{ steps.meta.outputs.tags[0] }}
          echo $KUBECONFIG_BAS64 | base64 -d > ~/.kube/config
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o kubcetl
          chmod a+x kubectl
          sed -i "s/DOCKER_IMAGE/$TAG/g" app.yaml
          kubectl apply -f app.yaml -n default
