name: GitHub Actions Demo
on: [push]
env:
  KUBECONFIG_BAS64: ${{ secrets.KUBECONFIG }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          mkdir -p ~/.kube/
          echo $KUBECONFIG_BAS64 | base64 -d > ~/.kube/config
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o kubcetl
          chmod a+x kubectl
          kubectl apply -f ingress.yaml
          kubectl delete -f ingress.yaml
